### ISSUE TITLE
Can not download data from AWS

### ISSUE THREAD

**Issue by meersonv** [geoglows/pygeoglows#46]
Hello,

Starting on Feb, 5 I can not download data.
I guesss it happened because a geoglows version change (I have 1.7.0).
I tried to install 1.8.1, but it requires version 2.18.4 of zarr (I have 2.18.2  - this is the latest version for RHEL-9)
What you recommend doing?

Regards, Vladimir Meerson
Israel Meteorological Service

**Comment by rileyhales** [comment]
Hi Vladimir. I've released v1.8.2 which loosens the required version of zarr. it will be available on pypi in the next few minutes and on conda within a few hours. That should resolve your issue.

**Comment by meersonv** [comment]
Dear Riley,

Thank you very much.
I will be able to check the new version on Sunday.

Best regards, Vladimir

**Comment by meersonv** [comment]
Dear Riley,
I installed 1.8.2 of geoglows (carr version 2.0.0 was also installed instead of 2.18,2)
Unfortunately, the script still doesn't work.
I get the following error when running: _**module 'zarr' has no attribute 'open_consolidated'**_
It seems that the requirement "zarr==2" is not sufficient.

Thank you

**Comment by rileyhales** [comment]
The zarr==2 requirement means that conda will attempt to install the latest version of zarr with the major version of 2. That explicitly prevents installing zarr 3 which has many bugs and breaking changes. In your case, you should get 2.18.2 if thats the latest on your RHEL machine.

**Comment by meersonv** [comment]
I used "pip install geoglows" command
During the installation zarr 2.18.2 was uninstalled and zarr 2.0.0 was installed instead

_Installing collected packages: zarr, geoglows
  Attempting uninstall: zarr
    Found existing installation: zarr 2.18.2
    Uninstalling zarr-2.18.2:
      Successfully uninstalled zarr-2.18.2
Successfully installed geoglows-1.8.2 zarr-2.0.0_

Do I  have to use conda to install?
